#include "autopoiesis/simulation.hpp"
#include "autopoiesis/renderer.hpp"
#include <chrono>
#include <thread>
#include <algorithm>
namespace apo {
Decision LocalDecider::decide(const Perception& p) { const auto& me=p.value["self"]; auto acts=p.value["available_actions"].get<std::vector<std::string>>(); if(me["hunger"]>=75 && std::find(acts.begin(),acts.end(),"eat_berries")!=acts.end()) return {DecisionType::Action,"eat_berries",json::object(),"I need food"}; if(me["fatigue"]>=75) return {DecisionType::Action,"sleep",json::object(),"I need rest"}; auto dirs=std::vector<std::string>{"north","south","east","west"}; return {DecisionType::Action,"move",{{"direction",dirs[std::uniform_int_distribution<size_t>(0,3)(rng_)]}},"I explore"}; }
Simulation::Simulation(unsigned seed,IDecider& d,Logger& l,ICycleReporter* reporter):world_(seed),decider_(d),logger_(l),reporter_(reporter),rng_(seed){ agents_={{"a1","Ada",{3,2},100,45,20,{90,20,30,30,40}},{"a2","Borin",{10,5},100,55,15,{25,85,70,90,40}},{"a3","Cyra",{16,7},100,35,60,{40,45,95,55,90}}}; }
Perception Simulation::perceive(Agent& a) { json cells=json::array(); for(int dy=-3;dy<=3;++dy)for(int dx=-3;dx<=3;++dx){Position p{a.position.x+dx,a.position.y+dy};if(std::abs(dx)+std::abs(dy)<=3&&world_.in_bounds(p)){auto terrain=world_.terrain(p);a.remember_map(p,terrain);cells.push_back({{"x",p.x},{"y",p.y},{"terrain",static_cast<int>(terrain)},{"rabbit",p==world_.rabbit()}});}} json known=json::array();for(const auto&[position,terrain]:a.map_memory)known.push_back({{"x",position.first},{"y",position.second},{"terrain",static_cast<int>(terrain)}}); json visible=json::array();for(const auto&o:agents_)if(o.alive&&o.id!=a.id&&std::abs(o.position.x-a.position.x)+std::abs(o.position.y-a.position.y)<=3)visible.push_back({{"id",o.id},{"name",o.name},{"x",o.position.x},{"y",o.position.y}});json mem=json::array();for(const auto&s:a.memories)mem.push_back(s);return Perception{json{{"self",{{"id",a.id},{"name",a.name},{"x",a.position.x},{"y",a.position.y},{"health",a.health},{"hunger",a.hunger},{"fatigue",a.fatigue},{"personality",personality_json(a.personality)}}},{"cells",cells},{"known_map",known},{"visible_agents",visible},{"memories",mem},{"available_actions",available_actions(a,world_,agents_)}}}; }
void Simulation::update_needs(Agent&a){a.hunger=clamp_stat(a.hunger+3);a.fatigue=clamp_stat(a.fatigue+2);if(a.hunger>=90){++a.critical_hunger_cycles;if(a.critical_hunger_cycles>3)a.health=clamp_stat(a.health-5);}else a.critical_hunger_cycles=0;if(a.health==0)a.alive=false;}
std::string Simulation::execute(Agent&a,const Decision&d){if(d.type==DecisionType::Blocked){a.remember("I reported a blockage: "+d.obstacle);return "signale un blocage : "+d.obstacle;}if(d.action=="wait"||d.action=="observe"){a.remember(d.action=="wait"?"J'ai attendu.":"J'ai observe mon environnement.");return "attend";}if(d.action=="sleep"){a.sleeping_cycles=2;a.fatigue=clamp_stat(a.fatigue-20);a.remember("Je commence a dormir.");return "commence a dormir";}if(d.action=="eat_berries"){if(world_.eat_berries(a.position)){a.hunger=clamp_stat(a.hunger-35);return "mange des baies";}return "ne peut pas manger ici";}if(d.action=="move"){auto dir=d.parameters["direction"].get<std::string>();Position p=a.position;if(dir=="north")--p.y;if(dir=="south")++p.y;if(dir=="east")++p.x;if(dir=="west")--p.x;if(world_.passable(p)){a.position=p;a.remember("Je me suis deplace vers "+dir+".");return "se deplace vers "+dir;}a.remember("Mon deplacement vers "+dir+" a ete bloque par un obstacle.");return "deplacement bloque";}if(d.action=="talk"){auto id=d.parameters["target_agent_id"].get<std::string>();for(auto&o:agents_)if(o.id==id){std::string msg=d.parameters.value("message","Bonjour.");a.remember("J'ai parle a "+o.name+" : "+msg);o.remember(a.name+" m'a parle : "+msg);return "parle a "+o.name;}}return "attend";}
void Simulation::cycle(){++cycle_;world_.advance_nature(rng_);for(auto&a:agents_)if(a.alive)update_needs(a);for(auto&a:agents_)if(a.alive){if(a.sleeping_cycles>0){--a.sleeping_cycles;a.fatigue=clamp_stat(a.fatigue-15);logger_.message("Cycle "+std::to_string(cycle_)+" — "+a.name+" dort.");continue;}Agent before=a;Decision d=decider_.decide(perceive(a));std::string e;if(!validate_decision(d,a,world_,agents_,e)){d={DecisionType::Action,"wait",json::object(),"invalid decision"};logger_.message("Cycle "+std::to_string(cycle_)+" — "+a.name+" decision invalide : "+e);}if(d.type==DecisionType::Blocked) logger_.feature_request(cycle_,a,d);auto result=execute(a,d);logger_.event(cycle_,before,d,result,a);}}
void Simulation::run(int cycles,int delay_ms,int render_every){for(int i=0;i<cycles;++i){cycle();if(reporter_)for(auto& agent:agents_)if(agent.alive){auto report=reporter_->report_cycle(cycle_,agent);if(!report.is_null())logger_.ai_report(cycle_,agent,report);}bool all_dead=std::none_of(agents_.begin(),agents_.end(),[](const Agent&a){return a.alive;});if(all_dead)logger_.message("Simulation arrêtée : tous les personnages sont morts.");if((render_every>0&&cycle_%render_every==0)||all_dead)render(cycle_,world_,agents_,logger_);if(all_dead)break;if(delay_ms>0)std::this_thread::sleep_for(std::chrono::milliseconds(delay_ms));}}
}
